#!/usr/bin/env python
# -*- coding: utf-8 -*-
import requests
from bs4 import BeautifulSoup
import urllib.parse
import re
import util

url = 'http://hanyu.baidu.com/'
h_file = 'header.txt'

#获取所有的script标签资源
def get_script_link(url):
    links = []
    header = util.load_header('../header.txt')
    resp = requests.get(url)
    resp.encoding = 'utf-8'
    bsobj = BeautifulSoup(resp.text, 'html.parser')
    spts = bsobj.find_all('script')
    for spt in spts:
        if 'src' in spt.attrs:
            links.append(spt['src'])
    return links

def query_word(string):
    string = 'http://hanyu.baidu.com/s?wd=%s&from=poem' % string
    urlcode = urllib.parse.quote(string, safe='?:/&=', encoding='utf-8')
    return urlcode

def get_pronounce(word):
    header = util.load_header(h_file)
    query_url = query_word(word)
    resp = requests.get(query_url, headers=header)
    resp.encoding = 'utf-8'
    bsobj = BeautifulSoup(resp.text, 'html.parser')
    div = bsobj.find('div', class_='pronounce')
    pron = div.span.b.string
    return pron

if __name__ == '__main__':
    pron = get_pronounce('谶')
    print(pron)